// strategy/my_strategy.h (or wherever your strategy is defined)
#include "utils/prediction_loader.h"
#include "order_manager.h" // Assuming you have an order management system
#include "market_types.h"
#include "events/event_system.h"
#include <string>
#include <chrono> // For getting current date
#include <iomanip> // For formatting date

class MyStrategy {
public:
    MyStrategy(EventSystem* event_system, OrderManager* order_manager);

    void onMarketUpdate(const MarketUpdateEvent& event);

private:
    EventSystem* event_system_;
    OrderManager* order_manager_;
    std::unordered_map<std::string, DailyPredictions> latest_predictions_;
    std::string last_loaded_file_;
    std::chrono::steady_clock::time_point last_load_time_;

    // Path to the JSON file generated by Python
    std::string prediction_file_path_ = "qlib_predictions.json";

    void updatePredictionsIfNeeded();
    std::string getCurrentDateStr(); // Helper to get YYYY-MM-DD format
    void executeSignal(const std::string& instrument, const PredictionRecord& prediction);
};

// strategy/my_strategy.cpp
MyStrategy::MyStrategy(EventSystem* event_system, OrderManager* order_manager)
    : event_system_(event_system), order_manager_(order_manager) {
    // Subscribe to market updates
    event_system_->subscribe(MarketUpdateEvent::EventType(), this);
}

void MyStrategy::onMarketUpdate(const MarketUpdateEvent& event) {
    // 1. 更新预测数据（如果文件有更新）
    updatePredictionsIfNeeded();

    // 2. 获取当前市场数据 (假设来自 MarketService)
    auto& cache = MarketService::Instance().getCache(); // Or however you access your market data
    std::string current_inst = "m2509"; // Example instrument
    auto current_tick = cache.getLatestTick(current_inst);

    if (current_tick.symbol.empty()) {
        return; // No data for this instrument yet
    }

    // 3. 获取今天的预测信号
    std::string today_str = getCurrentDateStr();
    PredictionRecord prediction = PredictionLoader::GetPrediction(latest_predictions_, today_str, current_inst);

    // 4. 根据信号执行下单逻辑
    if (prediction.signal == "BUY") {
        std::cout << "[Strategy] 收到 BUY 信号，为 " << current_inst << ", Score: " << prediction.score << std::endl;
        // Place buy order
        order_manager_->placeOrder(OrderRequest{
            .instrument = current_inst,
            .side = OrderSide::BUY,
            .quantity = 1, // Define quantity logic
            .price = current_tick.last_price, // Or use limit price based on strategy
            .type = OrderType::MARKET // Or LIMIT
            });
    }
    else if (prediction.signal == "SELL") {
        std::cout << "[Strategy] 收到 SELL 信号，为 " << current_inst << ", Score: " << prediction.score << std::endl;
        // Place sell order
        order_manager_->placeOrder(OrderRequest{
            .instrument = current_inst,
            .side = OrderSide::SELL,
            .quantity = 1, // Define quantity logic
            .price = current_tick.last_price, // Or use limit price based on strategy
            .type = OrderType::MARKET // Or LIMIT
            });
    }
    else {
        // HOLD or no signal
        std::cout << "[Strategy] HOLD 信号或无信号，为 " << current_inst << std::endl;
    }
}

void MyStrategy::updatePredictionsIfNeeded() {
    std::ifstream file(prediction_file_path_);
    if (!file.is_open()) {
        return; // File doesn't exist or can't be opened
    }

    auto current_time = std::filesystem::last_write_time(file); // Requires C++17
    file.close();

    // Compare modification time
    if (last_load_time_ < current_time || last_loaded_file_ != prediction_file_path_) {
        std::cout << "[Strategy] 检测到预测文件更新，正在加载..." << std::endl;
        latest_predictions_ = PredictionLoader::LoadPredictions(prediction_file_path_);
        last_load_time_ = current_time;
        last_loaded_file_ = prediction_file_path_;
    }
}

std::string MyStrategy::getCurrentDateStr() {
    auto now = std::chrono::system_clock::now();
    auto time_t_now = std::chrono::system_clock::to_time_t(now);
    std::stringstream ss;
    ss << std::put_time(std::localtime(&time_t_now), "%Y-%m-%d");
    return ss.str();
}

void MyStrategy::executeSignal(const std::string& instrument, const PredictionRecord& prediction) {
    // This function was integrated into onMarketUpdate above for simplicity.
    // You can separate it if needed.
}